worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    # Tối ưu hoá mạng
    sendfile on;

    server {
        listen 80;
        
        # Bật CORS ở cổng Gateway để App Flutter / Postman gọi không bị chặn
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';

        # Router 1: Dịch vụ Quản lý Thu Chi (Transaction Service)
        location /transactions {
            # Ngăn chặn lỗi CORS Preflight
            if ($request_method = 'OPTIONS') {
                return 204;
            }
            
            # proxy_pass: Bẻ lái thẳng vô container phía sau đang ẩn danh
            proxy_pass http://transaction_service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Router 2: Dịch vụ Chatbot AI
        location /chat {
            if ($request_method = 'OPTIONS') {
                return 204;
            }
            proxy_pass http://chatbot_service:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Kiểm tra Gateway Health
        location / {
            default_type application/json;
            return 200 '{"status":"API Gateway is running properly", "version":"1.0.0"}';
        }
    }
}
